// packages/react/src/components/ProjectTable.tsx
import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import {ProjectTableCell} from './ProjectTableCell';
import {ProjectTableHeaderCell} from './ProjectTableHeaderCell';
import {AuthHandler} from './AuthHandler';
import { Entity, getEntities, getProject, Project } from '@v7-product-interview-task/api';

// Custom hook to replace Vue's store functionality
const useStore = () => {
  const [apiKey, setApiKey] = useState('');
  const [isValid, setIsValid] = useState(false);
  const [entities, setEntities] = useState<Entity[]>([]);
  const [project, setProject] = useState<Project | null>(null);

  return {
    apiKey: {
      token: apiKey,
      setToken: setApiKey,
      isValid,
      setIsValid
    },
    entities: {
      list: entities,
      setEntities
    },
    project: {
      data: project,
      setProject
    }
  };
};

// Custom hook to handle project channel (you'll need to implement the actual WebSocket logic)
const useProjectChannel = (projectId: string) => {
  useEffect(() => {
    // Implement WebSocket connection logic here
    return () => {
      // Cleanup WebSocket connection
    };
  }, [projectId]);
};

export const ProjectTable = () => {
  const {workspaceId, projectId} = useParams() as { workspaceId: string; projectId: string };
   const store = useStore();
  
  useProjectChannel(projectId);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const projectData = await getProject({
          apiKey: import.meta.env.VITE_API_KEY,
          projectId,
          workspaceId
        });

        const entitiesData = await getEntities({
          apiKey: import.meta.env.VITE_API_KEY,
          projectId,
          workspaceId
        });

        store.project.setProject(projectData);
        store.entities.setEntities(entitiesData);
        store.apiKey.setIsValid(true);
      } catch {
        store.apiKey.setIsValid(false);
        store.entities.setEntities([]);
        store.project.setProject(null);
      }
    };

      fetchData();
  }, [store.apiKey.token, projectId, workspaceId]);

  return (
    <div className="flex flex-col gap-4 h-full p-2">
      <AuthHandler />

      {store.project.data && (
        <table 
          className="min-w-full border-collapse"
          role="grid"
          style={{ 
            gridTemplateColumns: `repeat(${store.project.data.properties.length}, 1fr)` 
          }}
        >
          <thead>
            <tr>
              <th />
              {store.project.data.properties.map((property, index) => (
                <ProjectTableHeaderCell
                  key={property.id}
                  property={property}
                  columnIndex={index}
                />
              ))}
            </tr>
          </thead>
          <tbody>
            {store.entities.list.map((entity, entityIndex) => (
              <tr key={entity.id}>
                <td tabIndex={0}>
                  <Link
                    to={`/workspace/${workspaceId}/project/${projectId}/entity/${entity.id}`}
                  >
                    {entityIndex + 1}
                  </Link>
                </td>
                {store.project.data?.properties.map((property, propertyIndex) => (
                  <ProjectTableCell
                    key={property.id}
                    field={entity.fields[property.slug]}
                    entityIndex={entityIndex}
                    propertyIndex={propertyIndex}
                  />
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      )}

      <style jsx>{`
        td, th {
          text-align: left;
          border: 1px solid grey;
        }

        td {
          position: relative;
          vertical-align: top;
          padding: 0.5rem;
        }

        td:focus, th:focus {
          outline: 2px solid deepskyblue;
        }
      `}</style>
    </div>
  );
};

export default ProjectTable;

// src/components/ProjectTable.vue
<script setup lang="ts">
import { getEntities } from '@/backend/getEntities'
import { getProject } from '@/backend/getProject'
import ProjectTableCell from '@/components/ProjectTableCell.vue'
import ProjectTableHeaderCell from '@/components/ProjectTableHeaderCell.vue'
import { useProjectChannel } from '@/composables/useProjectChannel'
import { useApiKeyStore } from '@/stores/apiKey'
import { useEntitiesStore } from '@/stores/entities'
import { useProjectStore } from '@/stores/project'
import { watch } from 'vue'
import AuthHandler from './AuthHandler.vue'

const props = defineProps<{
  workspaceId: string
  projectId: string
}>()

const apiKeyStore = useApiKeyStore()
const entityStore = useEntitiesStore()
const projectStore = useProjectStore()

useProjectChannel(props.projectId)

watch(() => apiKeyStore.token, async (newTokenValue) => {
  if (!newTokenValue) {
    throw new Error('API Key is required')
  }

  try {
    projectStore.project = await getProject({
      apiKey: newTokenValue,
      projectId: props.projectId,
      workspaceId: props.workspaceId
    })

    entityStore.entities = await getEntities({
      apiKey: newTokenValue,
      projectId: props.projectId,
      workspaceId: props.workspaceId
    })

    apiKeyStore.isValid = true
  } catch (error) {
    // probably an invalid token
    apiKeyStore.isValid = false
    entityStore.entities = []
    projectStore.project = null
  }

}, {
  immediate: true
})
</script>

<template>
  <div class="container">
		<AuthHandler />

    <table class="grid" role="grid" v-if="projectStore.project"
      :style="{ gridTemplateColumns: `repeat(${projectStore.project.properties.length}, 1fr)` }">
      <thead>
        <th />
        <ProjectTableHeaderCell v-for="property, index in projectStore.project.properties"
          :key="property.id"
          :property="property"
          :column-index="index" />
      </thead>
      <tbody>
        <tr v-for="entity, entityIndex in entityStore.entities" :key="entity.id">
          <td tabindex="0">
            <RouterLink :to="{
              name: 'entity',
              params: {
                workspaceId: props.workspaceId,
                projectId: props.projectId,
                entityId: entity.id
              }
            }">
              {{ entityIndex + 1 }}
            </RouterLink>
          </td>
          <ProjectTableCell v-for="property, propertyIndex in projectStore.project.properties"
            :key="property.id"
            :field="entity.fields[property.slug]"
            :entity-index="entityIndex"
            :property-index="propertyIndex" />
        </tr>
      </tbody>
    </table>

  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
	height: 100%;
  padding: 0.5rem;
}

.auth-token-config {
  display: flex;
  align-items: center;
  gap: 8px;
}

table {
  min-width: 100%;
  border-collapse: collapse;
}

td, th {
	text-align: left;
  border: 1px solid grey;
}

td {
  position: relative;
	vertical-align: top;
	padding: 0.5rem;

}

td:focus, th:focus {
  outline: 2px solid deepskyblue;
}
</style>
