// packages/react/src/components/ProjectTableCell.tsx
import { Entity } from '@v7-product-interview-task/api';
import React, { useRef } from 'react';
import styles from '@v7-product-interview-task/styles/ProjectTableCell.module.css'

type TableCellProps = {
  propertyIndex: number;
  entityIndex: number;
  field: Entity['fields'][string];
}

export const ProjectTableCell: React.FC<TableCellProps> = ({ propertyIndex, entityIndex, field }) => {
  const cellRef = useRef<HTMLTableCellElement>(null);

  const onClickCell = () => {
    cellRef.current?.focus();
  };

  const text = field?.tool_value.value?.toString() || field?.manual_value.value?.toString();

  return (
    <td
      className={styles.cell}
      ref={cellRef}
      role="gridcell"
      aria-rowindex={entityIndex + 1}
      aria-colindex={propertyIndex + 1}
      tabIndex={0}
      onClick={onClickCell}
    >
      {text ? (
        <span>{text}</span>
      ) : (
        <span className="emptyCell">(empty)</span>
      )}
    </td>
  );
};

export default ProjectTableCell;

// packages/vue/src/components/ProjectTableCell.vue
<script setup lang="ts">
import type { Entity } from '@v7-product-interview-task/api'
import { computed, ref } from "vue";

const props = defineProps<{
  propertyIndex: number;
  entityIndex: number;
  field: Entity["fields"][string];
}>();

const cellRef = ref<HTMLTableCellElement | null>(null);
const onClickCell = () => {
  if (cellRef.value) {
    cellRef.value.focus();
  }
};

const text = computed(() => {
  return (
    props.field?.tool_value.value?.toString() ||
    props.field?.manual_value.value?.toString()
  );
});
</script>

<template>
  <td
    class="cell"
    ref="cellRef"
    role="gridcell"
    :aria-rowindex="entityIndex + 1"
    :aria-colindex="propertyIndex + 1"
    tabindex="0"
    @click="onClickCell"
  >
    <span v-if="text">{{ text }}</span>
    <span v-else class="emptyCell">(empty)</span>
  </td>
</template>

<style scoped>
@import "@v7-product-interview-task/styles/ProjectTableCell.module.css";
</style>
