// packages/react/src/components/ProjectTableHeaderCell.tsx
import { Property } from "@v7-product-interview-task/api";
import styles from "@v7-product-interview-task/styles/ProjectTableHeaderCell.module.css"

export const ProjectTableHeaderCell = ({
  property,
  columnIndex,
}: {
  property: Property;
  columnIndex: number;
}) => {
  return (
    <th
      className={styles['header-cell']}
      role="gridcell"
      aria-rowindex={1}
      aria-colindex={columnIndex + 1}
      tabIndex={0}
    >
      {property.name}
      <span className={styles['property-type']}>({property.type})</span>
    </th>
  );
};

// packages/vue/src/components/ProjectTableHeaderCell.vue
<script setup lang="ts">
import type { Property } from '@v7-product-interview-task/api'

defineProps<{
  columnIndex: number;
  property: Property;
}>();
</script>

<template>
  <th
    class="header-cell"
    role="gridcell"
    aria-rowindex="1"
    :aria-colindex="columnIndex + 1"
    tabindex="0"
  >
    {{ property.name }}
    <span class="property-type">({{ property.type }})</span>
  </th>
</template>

<style scoped>
@import "@v7-product-interview-task/styles/ProjectTableHeaderCell.module.css";
</style>
