// packages/react/src/components/ProjectTable.tsx
import { Link, useParams } from 'react-router-dom';
import {ProjectTableCell} from './ProjectTableCell';
import {ProjectTableHeaderCell} from './ProjectTableHeaderCell';
import { useProjectContext } from '@/contexts/Project/useProjectContext';
import styles from '@v7-product-interview-task/styles/ProjectTable.module.css'


export const ProjectTable = () => {
  const {workspaceId, projectId} = useParams() as { workspaceId: string; projectId: string };
  const {entities, project} = useProjectContext()

  return (
    <div className={styles.container}>
      {project && (
        <table 
          className={styles.grid}
          role="grid"
          style={{ 
            gridTemplateColumns: `repeat(${project.properties.length}, 1fr)` 
          }}
        >
          <thead>
            <tr>
              <th />
              {project.properties.map((property, index) => (
                <ProjectTableHeaderCell
                  key={property.id}
                  property={property}
                  columnIndex={index}
                />
              ))}
            </tr>
          </thead>
          <tbody>
            {entities.map((entity, entityIndex) => (
              <tr key={entity.id}>
                <td tabIndex={0}>
                  <Link
                    to={`/${workspaceId}/projects/${projectId}/entities/${entity.id}`}
                  >
                    {entityIndex + 1}
                  </Link>
                </td>
                {project?.properties.map((property, propertyIndex) => (
                  <ProjectTableCell
                    key={property.id}
                    field={entity.fields[property.slug]}
                    entityIndex={entityIndex}
                    propertyIndex={propertyIndex}
                  />
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
};

export default ProjectTable;

// packages/vue/src/components/ProjectTable.vue
<script setup lang="ts">
import ProjectTableCell from '@/components/ProjectTableCell.vue'
import ProjectTableHeaderCell from '@/components/ProjectTableHeaderCell.vue'
import { useEntitiesStore } from '@/stores/entities'
import { useProjectStore } from '@/stores/project'
import { watch } from 'vue'
import {getEntities, getProject} from '@v7-product-interview-task/api'

const props = defineProps<{
  workspaceId: string
  projectId: string
}>()

const entityStore = useEntitiesStore()
const projectStore = useProjectStore()

watch(() => props.projectId, async () => {
  const apiKey = import.meta.env.VITE_API_KEY
  if (!apiKey) {
    throw new Error('API Key is required')
  }

  try {
    projectStore.project = await getProject({
      apiKey,
      projectId: props.projectId,
      workspaceId: props.workspaceId
    })

    entityStore.entities = await getEntities({
      apiKey,
      projectId: props.projectId,
      workspaceId: props.workspaceId
    })

  } catch (error) {
    // probably an invalid token
    entityStore.entities = []
    projectStore.project = null
  }

}, {
  immediate: true
})
</script>

<template>
  <div class="container">
    <table class="grid" role="grid" v-if="projectStore.project"
      :style="{ gridTemplateColumns: `repeat(${projectStore.project.properties.length}, 1fr)` }">
      <thead>
        <tr>
        <th />
        <ProjectTableHeaderCell v-for="property, index in projectStore.project.properties"
          :key="property.id"
          :property="property"
          :column-index="index" />
        </tr>
      </thead>
      <tbody>
        <tr v-for="entity, entityIndex in entityStore.entities" :key="entity.id">
          <td tabindex="0">
            <RouterLink :to="{
              name: 'entity',
              params: {
                workspaceId: props.workspaceId,
                projectId: props.projectId,
                entityId: entity.id
              }
            }">
              {{ entityIndex + 1 }}
            </RouterLink>
          </td>
          <ProjectTableCell v-for="property, propertyIndex in projectStore.project.properties"
            :key="property.id"
            :field="entity.fields[property.slug]"
            :entity-index="entityIndex"
            :property-index="propertyIndex" />
        </tr>
      </tbody>
    </table>

  </div>
</template>

<style scoped>
@import "@v7-product-interview-task/styles/ProjectTable.module.css";
</style>
